#ifndef FILES_IDL
#define FILES_IDL

#include "io.idl"

module files {

    exception PermissionDenied { };
    exception FileLocked { };
    exception FileInUse { };
    exception FileAlreadyExists { };
    exception InvalidName { };
    exception NoSuchFile { };

    interface Node;
    typedef sequence<Node> NodeSeq;

    interface FileCallback {
        void notify_file_changed(in Node file);
    };

    interface FileSystem {
        NodeSeq get_roots();
        Node find_file(in string path) raises (NoSuchFile);
        void register_callback(in FileCallback cb);
        void unregister_callback(in FileCallback cb);
    };

    enum FileType {
        FILE_REGULAR,
        FILE_DIR,
        FILE_SYMLINK,
        FILE_DEV,
        FILE_PIPE,
        FILE_SOC
    };
    
    interface Node {
        attribute string name setraises (PermissionDenied, FileAlreadyExists, InvalidName);
        readonly attribute long size;
        readonly attribute long permission;
        readonly attribute FileType type;
    };

	interface Directory : Node {
	    NodeSeq get_children() raises (PermissionDenied);
        Node get_child(in string name) raises (PermissionDenied, NoSuchFile);
        Node new_node(in string name, in FileType type) raises 
            (PermissionDenied, NodeAlreadyExists, InvalidName)
	}; 
	
	interface Lock {
	   void unlock();
	};
    
    interface File : Node {
        Lock lock_read() raises (PermissionDenied, FileLocked, FileInUse);
        Lock lock_write() raises (PermissionDenied, FileLocked, FileInUse);
        io::InputStream begin_read() raises (PermissionDenied, FileLocked);
        io::OutputStream begin_write() raises (PermissionDenied, FileLocked);
        io::IOStream begin_io() raises (PermissionDenied, FileLocked);
    };

};

#endif // FILES_IDL
